# Generated by Django 2.2.9 on 2020-04-17 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('s_admin', '0002_areamodel_citymodel_restauranttypemodel_statemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResturantModel',
            fields=[
                ('rest_id', models.AutoField(primary_key=True, serialize=False)),
                ('rest_name', models.CharField(max_length=30, unique=True)),
                ('rest_contact', models.IntegerField(unique=True)),
                ('rest_email', models.EmailField(max_length=100, unique=True)),
                ('rest_password', models.CharField(max_length=30)),
                ('res_otp', models.IntegerField()),
                ('res_status', models.CharField(default=False, max_length=30)),
                ('rest_area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.AreaModel')),
                ('rest_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='s_admin.RestaurantTypeModel')),
            ],
        ),
    ]
